// islands/Sidebar.tsx
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faBars,
  faCircleHalfStroke,
  faIdCardClip,
  faImages,
  faMoon,
  faSun,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { useEffect, useState } from "preact/hooks";
import { Button } from "@/components/ui/button.tsx";
import { Card } from "@/components/ui/card.tsx";
import { Separator } from "@/components/ui/separator.tsx";
import { FaIcon } from "@/components/icon.tsx";
import {
  getStoredTheme,
  type Theme,
  updateTheme,
  watchSystemTheme,
} from "@/lib/theme.ts";

const socialMediaIcons: { url: string; icon: IconDefinition }[] = [
  { url: "https://github.com/ptchtrns", icon: faGithub },
  { url: "https://www.linkedin.com/in/ptchtrns/", icon: faLinkedin },
];

const navItems: {
  title: string;
  url: string;
  /** Prefix used to highlight this item for nested routes, e.g. media's tabs. */
  matchPrefix?: string;
  icon: IconDefinition;
}[] = [
  { title: "About me", url: "/", icon: faUser },
  { title: "Contact me", url: "/contact", icon: faIdCardClip },
  {
    title: "Media",
    url: "/media/photos",
    matchPrefix: "/media",
    icon: faImages,
  },
];

const themes: { theme: Theme; icon: IconDefinition }[] = [
  { theme: "dark", icon: faMoon },
  { theme: "light", icon: faSun },
  { theme: "system", icon: faCircleHalfStroke },
];

interface SidebarProps {
  /** Current pathname, used to highlight the active nav item. */
  path: string;
  /** Profile picture URL fetched from the media table, or null if none is set. */
  pfpSrc: string | null;
}

export default function Sidebar({ path, pfpSrc }: SidebarProps) {
  const [isOpen, setIsOpen] = useState(false);
  // Content nav is swapped via a Fresh Partial, so the layout (and this
  // island) never re-renders on navigation — track the active path ourselves.
  const [activePath, setActivePath] = useState(path);
  const [activeTheme, setActiveTheme] = useState<Theme>("system");

  useEffect(() => {
    setActiveTheme(getStoredTheme());
    return watchSystemTheme(setActiveTheme);
  }, []);

  useEffect(() => {
    const onPopState = () => setActivePath(globalThis.location.pathname);
    addEventListener("popstate", onPopState);
    return () => removeEventListener("popstate", onPopState);
  }, []);

  return (
    <>
      <Button
        variant="outline"
        size="icon"
        onClick={() => setIsOpen(!isOpen)}
        aria-label="Open menu"
        class="md:hidden fixed top-6 left-0 z-50 rounded-l-none rounded-r-lg border-l-0 bg-white dark:bg-stone-800 border-stone-300 dark:border-stone-600 active:scale-95"
      >
        <FaIcon icon={faBars} class="text-stone-800 dark:text-stone-200" />
      </Button>

      <div
        class={[
          "fixed top-0 left-0 bottom-0 right-0 z-40 backdrop-blur-3xl bg-gradient",
          "bg-linear-to-br via-transparent from-black/25 to-transparent dark:from-white/10 dark:to-white/5",
          isOpen ? "block md:hidden fixed" : "hidden",
        ].join(" ")}
        onClick={() => setIsOpen(false)}
      />

      <nav
        class={[
          "fixed z-40 w-64 xl:w-72 my-6 mx-12 transition-transform duration-300 md:translate-x-0",
          isOpen ? "translate-x-0" : "-translate-x-120",
        ].join(" ")}
      >
        <Card class="bg-white dark:bg-stone-900 rounded-[17px] flex flex-col p-3 border border-stone-300 dark:border-stone-700">
          <div class="px-3 pt-2 flex flex-col gap-2.5">
            {pfpSrc && (
              <img
                src={pfpSrc}
                alt="Nikolai Zakharov"
                class="rounded-full w-32"
              />
            )}
            <div>
              <h2 class="font-bold text-xl dark:text-stone-100">
                Nikolai Zakharov
              </h2>
              <span class="text-stone-700 dark:text-stone-400">@ptchtrns</span>
            </div>
          </div>

          <ul class="flex flex-col">
            {navItems.map((navItem) => {
              const active = navItem.matchPrefix
                ? activePath.startsWith(navItem.matchPrefix)
                : activePath === navItem.url;
              return (
                <li key={navItem.url}>
                  <a
                    href={navItem.url}
                    onClick={() => {
                      setActivePath(navItem.url);
                      setIsOpen(false);
                    }}
                    class={[
                      "w-full py-1.5 px-3 flex gap-4",
                      active
                        ? "font-bold text-stone-950 dark:text-white"
                        : "text-stone-700 dark:text-stone-300",
                      "hover:text-stone-950 dark:hover:text-white",
                      "hover:bg-linear-to-r from-stone-100 via-stone-100 to-stone-50 dark:from-stone-800 dark:via-stone-800 dark:to-stone-900",
                      "border border-transparent hover:border-stone-200 dark:hover:border-stone-600",
                      "rounded-lg active:scale-99 transition-all",
                    ].join(" ")}
                  >
                    <span class="w-4">
                      <FaIcon icon={navItem.icon} />
                    </span>
                    <span>{navItem.title}</span>
                  </a>
                </li>
              );
            })}
          </ul>

          <Separator />

          <footer class="flex flex-col gap-2">
            <div class="flex">
              {socialMediaIcons.map((socialMediaIcon) => (
                <Button
                  key={socialMediaIcon.url}
                  variant="ghost"
                  size="icon"
                  href={socialMediaIcon.url}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <FaIcon icon={socialMediaIcon.icon} class="text-lg" />
                </Button>
              ))}
            </div>
          </footer>
        </Card>

        <div class="flex justify-between mt-4">
          <Card class="bg-white dark:bg-stone-900 rounded-[17px] flex flex-row p-1 border border-stone-300 dark:border-stone-700 gap-0">
            {themes.map((theme) => (
              <Button
                key={theme.theme}
                variant="ghost"
                size="icon-sm"
                class={activeTheme === theme.theme
                  ? "bg-stone-200 dark:bg-stone-700 font-bold text-stone-950 dark:text-white"
                  : "text-stone-400 dark:text-stone-500"}
                aria-label={`Use ${theme.theme} theme`}
                onClick={() => {
                  updateTheme(theme.theme);
                  setActiveTheme(theme.theme);
                }}
              >
                <FaIcon icon={theme.icon} />
              </Button>
            ))}
          </Card>

          <div class="flex gap-2">
            {/* Language switching placeholder */}
          </div>
        </div>
      </nav>
    </>
  );
}

// frontend/src/components/Sidebar.vue
<template>
  <button
    @click="isOpen = !isOpen"
    class="md:hidden fixed top-6 left-0 z-50 bg-white dark:bg-stone-800 p-1.5 rounded-r-lg border-r border-b border-t border-stone-300 dark:border-stone-600 active:scale-95 transition-all"
  >
    <FontAwesomeIcon :icon="faBars" class="text-xl text-stone-800 dark:text-stone-200" />
  </button>

  <div :class="[
    'fixed top-0 left-0 bottom-0 right-0 backdrop-blur-3xl bg-gradien',
    'bg-linear-to-br via-transparent from-black/25 to-transparent dark:from-white/10 dark:to-white/5',
    isOpen ? 'block md:hidden fixed' : 'hidden']"
  />

  <nav
    :class="[
      'fixed w-64 xl:w-72 my-6 mx-12 transition-transform duration-300 md:translate-x-0',
      isOpen ? 'translate-x-0' : '-translate-x-120'
    ]"
  >
    <div class="bg-white dark:bg-stone-900 rounded-[17px] flex flex-col p-3 border border-stone-300 dark:border-stone-700">
      <div class="px-3 py-2 flex flex-col gap-2.5">
        <img src="/img/nikolai.jpg" alt="Nikolai Zakharov" class="rounded-full w-32" />
        <div>
          <h2 class="font-bold text-xl dark:text-stone-100">Nikolai Zakharov</h2>
          <span class="text-stone-700 dark:text-stone-400">&commat;ptchtrns</span>
        </div>
        <div class="flex gap-2">
          <a
            v-for="socialMediaIcon in socialMediaIcons"
            :key="socialMediaIcon.url"
            :href="socialMediaIcon.url"
            target="_blank"
            rel="noopener noreferrer"
            class="text-stone-700 dark:text-stone-300 hover:text-stone-950 dark:hover:text-white active:scale-92 transition-all"
          >
            <FontAwesomeIcon :icon="socialMediaIcon.icon" class="text-xl" />
          </a>
        </div>
      </div>

      <ul class="flex flex-col">
        <li v-for="navItem in navItems" :key="navItem.url">
          <RouterLink
            :to="navItem.url"
            class="w-full py-1.5 px-3 flex gap-4
              text-stone-700 dark:text-stone-300 hover:text-stone-950 dark:hover:text-white
              hover:bg-linear-to-r from-stone-100 via-stone-100 to-stone-50 dark:from-stone-800 dark:via-stone-800 dark:to-stone-900
              border border-transparent hover:border-stone-200 dark:hover:border-stone-600
              rounded-lg active:scale-99 transition-all"
          >
            <span class="w-4"><FontAwesomeIcon :icon="navItem.icon" /></span>
            <span>{{ navItem.title }}</span>
          </RouterLink>
        </li>
      </ul>
    </div>

    <footer class="px-6 flex justify-between mt-4">
      <div class="flex gap-2">
        <button
          v-for="theme in themes"
          :key="theme.theme"
          :class="[
            'cursor-pointer active:scale-92 transition-all',
            themeStore.currentTheme === theme.theme
              ? 'text-blue-700' 
              : 'text-stone-400 hover:text-stone-600 dark:text-stone-400 dark:hover:text-stone-200'
          ]"
          @click="theme.action"
        >
          <FontAwesomeIcon :icon="theme.icon" />
        </button>
      </div>

      <div class="flex gap-2">
        <!-- Language switching placeholder -->
      </div>
    </footer>
  </nav>
</template>


<script setup lang="ts">
import { RouterLink, useRoute } from 'vue-router';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faGithub, faLinkedin, type IconDefinition } from '@fortawesome/free-brands-svg-icons';
import { faBars, faCircleHalfStroke, faHeadphones, faIdCardClip, faImages, faListUl, faMoon, faSun, faUser } from '@fortawesome/free-solid-svg-icons';
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useThemeStore, type Theme } from '@/theme';

const isOpen = ref(false)
const route = useRoute();

// Close menu on route change
watch(
  () => route.fullPath,
  () => {
    isOpen.value = false;
  }
);
const socialMediaIcons = [
  {
    url: "https://github.com/ptchtrns",
    icon: faGithub,
  },
  {
    url: "https://www.linkedin.com/in/ptchtrns/",
    icon: faLinkedin,
  },
]
const navItems = [
  {
    title: "About me",
    url: "/",
    icon: faUser,
  },
  {
    title: "Services",
    url: "/services",
    icon: faListUl,
  },
  {
    title: "Contact me",
    url: "/contact",
    icon: faIdCardClip,
  },
  {
    title: "Gallery",
    url: "/gallery",
    icon: faImages,
  },
  {
    title: "Audio",
    url: "/audio",
    icon: faHeadphones,
  },
]

const themeStore = useThemeStore();

const themes: {theme: Theme, icon: IconDefinition, action: () => void}[] = [
  { theme: 'dark', icon: faMoon, action: () => themeStore.updateTheme('dark') },
  { theme: 'light', icon: faSun, action: () => themeStore.updateTheme('light') },
  { theme: 'system', icon: faCircleHalfStroke, action: () => themeStore.updateTheme('system') },
]
</script>
