// components/ui/card.tsx
import type { JSX } from "preact";
import { cn } from "@/lib/utils.ts";

type DivProps = JSX.IntrinsicElements["div"];

export function Card({ class: className, ...props }: DivProps) {
  return (
    <div
      data-slot="card"
      class={cn(
        "bg-card text-card-foreground flex flex-col gap-4 rounded-xl border py-6 shadow-sm",
        className,
      )}
      {...props}
    />
  );
}

export function CardHeader({ class: className, ...props }: DivProps) {
  return (
    <div
      data-slot="card-header"
      class={cn(
        "@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6",
        className,
      )}
      {...props}
    />
  );
}

export function CardTitle(
  { class: className, ...props }: JSX.IntrinsicElements["h3"],
) {
  return (
    <h3
      data-slot="card-title"
      class={cn("leading-none font-semibold", className)}
      {...props}
    />
  );
}

export function CardDescription(
  { class: className, ...props }: JSX.IntrinsicElements["p"],
) {
  return (
    <p
      data-slot="card-description"
      class={cn("text-muted-foreground", className)}
      {...props}
    />
  );
}

export function CardAction({ class: className, ...props }: DivProps) {
  return (
    <div
      data-slot="card-action"
      class={cn(
        "col-start-2 row-span-2 row-start-1 self-start justify-self-end",
        className,
      )}
      {...props}
    />
  );
}

export function CardContent({ class: className, ...props }: DivProps) {
  return (
    <div data-slot="card-content" class={cn("px-6", className)} {...props} />
  );
}

export function CardFooter({ class: className, ...props }: DivProps) {
  return (
    <div
      data-slot="card-footer"
      class={cn("flex items-center px-6 [.border-t]:pt-6", className)}
      {...props}
    />
  );
}

// frontend/src/components/ui/card/Card.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="card"
    :class="
      cn(
        'bg-card text-card-foreground flex flex-col gap-4 rounded-xl border py-6 shadow-sm',
        props.class,
      )
    "
  >
    <slot />
  </div>
</template>
